BrainsterPreneurs/routes/web.php
<?php

use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MyProjectsController;
//use App\Http\Controllers\StepOneController;
//use App\Http\Controllers\StepThreeController;
//use App\Http\Controllers\StepTwoController;
//use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('/stepOne', StepOneController::class)->only(['index', 'store']);
Route::resource('/stepTwo', StepTwoController::class)->only(['index', 'store']);
Route::resource('/stepThree', StepThreeController::class)->only(['index', 'store']);
Route::post('/stepThree-media', StepThreeController::class . "@mediaStore")->name('stepThree-media.store');

Route::resource('/home/my-projects', MyProjectsController::class);

Route::get('/home/my-projects/profile/{user}/{project}', MyProjectsController::class . '@applicantProfile')->name('my-projects.profile');
Route::post('/home/acceptApplicant', MyProjectsController::class. '@applicantAccept');
Route::post('/home/my-projects/project', MyProjectsController::class. '@projectComplete');

Route::get('/user-avatar', UserController::class . '@getAvatar')->name('current-user-avatar.get');
Route::get('/user-avatar/{user}', UserController::class . '@getAvatarByUser')->name('user-avatar.get');

Route::resource('/home/my-applications', MyApplicationsController::class)->only(['index', 'destroy']);
Route::resource('/home/my-profile', MyProfileController::class);

Route::post('/home/applications', [HomeController::class, 'getApplications']);

BrainsterPreneurs/resources/views/create_project.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 1])

@section('main_content')

    <form method="POST" action="{{route('my-projects.store')}}">
        @csrf
        <div class="row row-main">
            <div class="col-6">
                <div class="row my-5">
                    <div class=" col-10 ml-4 mb-5">
                        <h3>New Project</h3>
                    </div>
                    <div class="col-4 ml-4 mb-5">
                        <div class="form-group">
                            <input type="text" id="name" name="name" class="form-control font-weight-bold outline-none" placeholder="Name"/>
                            <div class="text-danger"></div>
                        </div>
                    </div>

                    <div class="col-10 ml-4">
                        <div class="form-group">
                            <label for="description" class="text-muted font-weight-bold mb-2">Description of project</label>
                            <textarea type="text" id="description" name="description" class="form-control font-weight-bold input-button-border"  style="background: transparent; border:none; " v-model="biography" ></textarea>
{{--                            <input type="text" id="description" name="description" class="form-control" placeholder="Lorem ipsum.." />--}}
                            <div class="text-danger"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="row my-5">
                    <div class="col-12 ml-4 mb-5">
                        <h3>What I need</h3>
                    </div>

                    <div class="row v-100 h-100">
                        <div class="col-12 v-100 h-100 d-flex flex-wrap">
                        @foreach($academies as $academy)
                            <div class="academy-card m-2">
                                <div class="box" ed="{{$academy->id}}">{{$academy->name}}</div>
                                <input type="hidden" name="academies[{{$academy->id}}]" value="0">
                            </div>
                        @endforeach
                    </div>

                    </div>

                    <div class="offset-6 col-6 mt-5 mb-4">
                        <strong class="options-text-orange">Please select no more than 4 options</strong>
                    </div>

                    <div class="offset-7 col-3 mt-5">
                        <button class="btn color-darkgreen-background
                         text-light font-weight-bold" type="submit">CREATE</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection


@push('link-script')
    <script src="{{ asset('js/create_project.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/edit_project.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 1])

@section('main_content')

    <form method="POST" action="{{route('my-projects.update', ['my_project' => $project])}}">
        @method('PUT')
        @csrf
        <div class="row row-main">
            <div class="col-6">
                <div class="row my-5">
                    <div class=" col-10 ml-4 mb-5">
                        <h3>Edit Project</h3>
                    </div>
                    <div class="col-4 ml-4 mb-5">
                        <div class="form-group">
                            <input type="text" id="name" name="name" class="form-control font-weight-bold outline-none" placeholder="Name" value="{{$project->name}}"/>
                            <div class="text-danger"></div>
                        </div>
                    </div>

                    <div class="col-10 ml-4">
                        <div class="form-group">
                            <label for="description" class="text-muted font-weight-bold mb-2">Description of project</label>
                            <textarea type="text" id="description" name="description" class="form-control font-weight-bold input-button-border"  style="background: transparent; border:none; " v-model="biography" >{{$project->description}}</textarea>
                            <div class="text-danger"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="row my-5">
                    <div class="col-12 ml-4 mb-5">
                        <h3>What I need</h3>
                    </div>

                    <div class="row v-100 h-100">
                        <div class="col-12 v-100 h-100 d-flex flex-wrap">
                            @foreach($academies as $academy)
                                <div class="academy-card m-2  @if($project->academies->where('id', $academy->id)->count() > 0) active @endif">
                                    <div class="box" ed="{{$academy->id}}">{{$academy->name}}</div>
                                    <input type="hidden" name="academies[{{$academy->id}}]" value="@if($project->academies->where('id', $academy->id)->count() > 0)1 @endif">
                                </div>
                            @endforeach
                        </div>

                    </div>
                    <div class="offset-6 col-6 mt-5 mb-4">
                        <strong class="options-text-orange">Please select no more than 4 options</strong>
                    </div>

                    <div class="offset-7 col-3 mt-5">
                        <button class="btn color-darkgreen-background
                         text-light font-weight-bold" type="submit">EDIT</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@push('link-script')
    <script src="{{ asset('js/create_project.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/home.blade.php
@extends('layouts.main')

@section('main_content')
    <div class="row pt-2 h-100">
        <div class="col-4">
            <div id="left-container">
                <div class="row ml-4">
                    <div class="col-12">
                        <div class="my-4 font-weight-bold">In what filed can you be amazing?</div>
                    </div>
                </div>

                <div class="row ml-4 mt-5">
                    <div class="col-10" id="academies-wrapper">
                        <div class="d-flex flex-wrap">
                            <button class="btnDesign mb-2 ml-2 active" data-id="-1">ALL</button>
                            @foreach($academies as $academy)
                                <button class="btnDesign mb-2 ml-2" data-id="{{$academy->id}}">{{$academy->name}}</button>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {{--            DESIGN NA KARTICA POPRAVI--}}


        <div class="col-8 h-100 overflow-hidden ">
            <div class="row card-explanation">
                <div class="col-10" style="max-width: 81%;">
                    <div class="d-flex justify-content-end">
                        <img class="arrow-img" src="{{asset('images/icons/3.png') }}" alt="">
                        <div class="my-4 fw-bold">Checkout the latest projects</div>
                    </div>
                </div>
            </div>
            <div id="cards-wrapper" style="height: calc(100% - 140px);">
                @include('_includes.home_cards')
            </div>
        </div>
    </div>
@endsection

@push('link-script')
    <script src="{{ asset('js/home.js') }}" defer></script>
    <script src="{{ asset('js/project-card.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/myApplications.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 2])

@section('main_content')

    <div class="row h-100 row-main">
        <div class="col-12" style="height: 50px">
            <h4>My Applications</h4>
        </div>

        <div class="col-12 mt-5" style="height: calc(100% - 95px)">
            <div class="my-project-cards">
                @foreach($user->memberProjects->sortByDesc('id') as $project)
                    @include('_includes.project-card', [
                                'project' => $project,
                                'showBadge' => 1,
                                'first' => $loop->index == 0 ? 1 : 0,
                                'className' => 'big',
                                'isEditable' => 1
                                ])
                @endforeach
            </div>
        </div>
    </div>
@endsection


@push('link-script')
    <script src="{{ asset('js/project-card.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/myProfile.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 3])

@section('main_content')

    <form method="post" action="{{route('my-profile.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="row row-main">
            <div class="col-5 mt-3">
                <h4>My Profile</h4>
                <div class="d-flex mt-4">
                    <div class="d-flex flex-column">
                        <div class="d-flex">
                            @if(count($user->attachment()) > 0)
                                <img class="img-myProfile mr-5" src="{{route('current-user-avatar.get')}}" alt="" />
                            @else
                                <img class="img-myProfile mr-5" src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg" alt="" />
                            @endif
                            <div class="d-flex flex-column m-5">
                                <input class="font-weight-bold input-withoutBorder" type="text" name="name" id="" value="{{$user->name}}" />
                                <input class="font-weight-bold input-withoutBorder" type="text" name="surname" id="" value="{{$user->surname}}" />
                                <input class="font-weight-bold input-withoutBorder" type="email" name="email" id="" value="{{$user->email}}" />
                            </div>
                        </div>
                        <div>
                            <p><small>Click here to upload an image
                                    <input type="file" id="image" name="image" class="form-control opacity-0" style="cursor: pointer"></small></p>
                        </div>
                    </div>
                </div>
                <div class="">
                    <p class="font-weight-bold" style="color: #949d99;">Biography:</p>
                    <textarea class="font-weight-bold" style="color: #949d99;" name="biography" id="biography">{{$user->biography}}</textarea>
                </div>
            </div>

            <div class="col-7 mt-3">
                <h4>Skills:</h4>



                <div class="d-flex">
                    <div>
                        <div class="col-12 justify-content-center d-grid gap-3 square mb-5 mt-5">
                            <div class="wrapper-scroll">
                                @foreach ($skills as $skill)
                                    <div class="skill-card-myProfile col-lg-2 col-md-3 col-xs-6 mt-3 mr-2 @if($user->skills->where('id', $skill->id)->count() > 0) active @endif" data-skillcard>
                                        <div class="box font-xx-small">{{$skill->name}}</div>
                                        <input type="hidden" name="skills[{{$skill->id}}]" value="@if($user->skills->where('id', $skill->id)->count() > 0)1 @endif">
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <button type="submit" class="color-darkgreen-background text-light float-right" style="margin-top: 150px;">EDIT</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection

@push('link-script')
    <script src="{{ asset('js/stepTwo.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/my_projects.blade.php
@extends('layouts.main')


@include('layouts.navbar-pages', ['page'=> 1])

@section('main_content')
<div class="row h-100 row-main">
    <div class="col-12" style="height: 50px">
        <div class="fw-bold">Have a new idea to make the world better?</div>
    </div>
    <div class="col-12" style="height: 50px">
        <form method="GET" action="{{route('my-projects.create')}}" class="d-flex">
            <h3 class="m-0 p-0">Create a new project</h3>
            <button class="ml-3 button-outline-none" type="submit">
                <img class="my_projects_icon" src="{{ asset('images/icons/1.png') }}" alt="" />
            </button>
{{--            <a href=""><img class="my_projects_icon mx-2" src="{{route('')}}" alt="" /></a>--}}
        </form>
    </div>

    <div class="col-12 mt-5" style="height: calc(100% - 150px)">
        <div class="my-project-cards">
            @foreach($user->createdProjects->sortByDesc('id') as $project)
                @include('_includes.project-card', [
                            'project' => $project,
                            'showBadge' => 1,
                            'first' => $loop->index == 0 ? 1 : 0,
                            'className' => 'big',
                            'isEditable' => 1
                            ])
            @endforeach
        </div>
    </div>
</div>

@endsection

@push('link-script')
    <script src="{{ asset('js/project-card.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/project-applicants.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 1])

@section('main_content')
    <div class="row row-main">
        <div class="col-sm-12 col-md-9">
            <h3 class="mb-5">{{$project->name}}</h3>
            <h5>Choose your temmates<img src=""/></h5>
        </div>
        <div class="col-sm-12 col-md-3">
            <div class="font-weight-light text-secondary">Ready to start?</div>
            <div class="font-weight-light text-secondary">Click on the button below</div>
            <button id="team-assembledBtn" class="team-assembledBtn mt-2 @if($project->locked) completed @endif" data-projectid="{{$project->id}}">TEAM ASSEMBLE
                @if($project->locked) <i class="fas fa-check"></i> @endif</button>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12">
            <div class="d-flex flex-row justify-content-center margin-top-applicants">
                @foreach($project->projectMember as $projectMember)
                    @include('_includes.project-applicants-card')
                @endforeach
            </div>
        </div>
    </div>
@endsection

@push('link-script')
    <script src="{{ asset('js/project-applicant.js') }}" defer></script>
@endpush

BrainsterPreneurs/resources/views/user_profile.blade.php
@extends('layouts.main')

@include('layouts.navbar-pages', ['page'=> 1])

@section('main_content')
    <div class="row row-main" style="height: 100%">
        <div class="col-12 ps-5 mt-5" style="height: calc(100% - 50px)">
            <div class="d-flex justify-content-between h-100">
                <div class="d-flex flex-column h-100">
                    <div class="d-flex flex-wrap">
                        @if(count($user->attachment()) > 0)
                            <img src="{{route('user-avatar.get', ['user' => $user->id])}}" class="img-profile me-5" />
                        @else
                            <img src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg" class="img-profile me-5" />
                        @endif
                        <div class="d-flex flex-column ml-5 justify-content-center">
                            <h4 class="color-gray">Name: </h4>
                            <h3>{{$user->name . ' ' . $user->surname}}</h3>
                            <h4 class="color-gray">Contact:</h4>
                            <h3>{{$user->email}}</h3>
                        </div>
                    </div>

                    <form action="{{route('my-projects.show', ['my_project' => $project])}}" method="get" class="d-flex h-100 align-items-end">
                        <div>
                            <button class="text-light btn-green" style="margin: 0 0 50px 0">BACK</button>
                        </div>
                    </form>

                </div>
                <div class="d-flex flex-column">
                    <h4 class="color-gray">Biography:</h4>
                    <p class="color-gray">{{$user->biography}}</p>
                    <p class="align-self-end">Show more</p>
                    <h4 class="color-gray mt-5">Skills:</h4>
                    <div class="d-flex flex-wrap justify-content-center">
                        @foreach($user->skills as $skill)
{{--skills-user-projects--}}
                            <div class="skills-user-projects">
                                <div class="">{{$skill->name}}</div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection