BrainsterPreneurs/routes/web.php
<?php

use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MyProjectsController;
//use App\Http\Controllers\StepOneController;
//use App\Http\Controllers\StepThreeController;
//use App\Http\Controllers\StepTwoController;
//use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('/stepOne', StepOneController::class)->only(['index', 'store']);
Route::resource('/stepTwo', StepTwoController::class)->only(['index', 'store']);
Route::resource('/stepThree', StepThreeController::class)->only(['index', 'store']);
Route::post('/stepThree-media', StepThreeController::class . "@mediaStore")->name('stepThree-media.store');

Route::resource('/home/my-projects', MyProjectsController::class);

Route::get('/home/my-projects/profile/{user}/{project}', MyProjectsController::class . '@applicantProfile')->name('my-projects.profile');
Route::post('/home/acceptApplicant', MyProjectsController::class. '@applicantAccept');
Route::post('/home/my-projects/project', MyProjectsController::class. '@projectComplete');

Route::get('/user-avatar', UserController::class . '@getAvatar')->name('current-user-avatar.get');
Route::get('/user-avatar/{user}', UserController::class . '@getAvatarByUser')->name('user-avatar.get');

Route::resource('/home/my-applications', MyApplicationsController::class)->only(['index', 'destroy']);
Route::resource('/home/my-profile', MyProfileController::class);

Route::post('/home/applications', [HomeController::class, 'getApplications']);

BrainsterPreneurs/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/login.js') }}" defer></script>
    @stack('link-script')

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    <link href="{{ mix('css/style.css') }}" rel="stylesheet">

    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-auto-replace-svg="nest"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    @yield('content')
</body>
</html>

BrainsterPreneurs/resources/views/layouts/dashboard.blade.php
@extends('layouts.app')


<main class="h-100 w-100 background-img-steps">
    <nav class="navbar navbar-expand-lg navbar-light" style=" height: 70px">
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link active"><h6 class="m-4 font-weight-bold text-large">
                        BRAINSTER<span class="text-secondary">PRENEURS</span></h6>
                </a>
            </div>
            <div class="navbar-nav ml-auto">
                <img class="home-page-image mt-3"
                     src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg">
            </div>
        </div>
    </nav>
    <hr class="text-decoration-none" style="height:3px; background: #dd7f1e;">

    <div class="container-fluid dashboard">
        @yield('content')
    </div>
</main>

BrainsterPreneurs/resources/views/layouts/main.blade.php
@extends('layouts.app')

@section('content')
<main class="h-100 w-100 background-img-steps">
    <nav class="navbar navbar-expand-lg navbar-light" style=" height: 50px; padding-top: 20px;">
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link active"><h6 class="m-4 font-weight-bold text-dark">
                        BRAINSTER<span class="text-secondary">PRENEURS</span></h6>
                </a>
            </div>
            <div class="navbar-nav ml-auto">
                @yield('navbar-pages')
                <form method="GET" action="@if(request()->path() == "home"){{route('my-projects.index')}}@else {{route('home')}} @endif" style="align-self: center;display: flex;">
                    <button class="outline-profile-img">
                        <img class="home-page-image"
                             @if($user->hasPhoto())
                                src="{{route('current-user-avatar.get')}}?t={{time()}}"
                             @else
                                src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg"
                            @endif
                             >
                    </button>
                </form>

            </div>
        </div>
    </nav>
    <hr class="text-decoration-none" style="height:3px; background: #dd7f1e;">

    <div class="container-fluid dashboard">
        @yield('main_content')
    </div>


</main>

<div class="modal fade" id="card-modal" tabindex="-1" aria-labelledby="registerModal-label" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="registerLabel">Message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-floating">
                    <textarea class="form-control" placeholder="Place your message here..." id="card-modal-message" style="height: 100px"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="card-modal-send" class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="card-modal-success" tabindex="-1" aria-labelledby="registerModal-label" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="registerLabel">Message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Your application was successfully submitted!</label>
            </div>
            <div class="modal-footer">
                <button type="button" id="card-modal-success" data-dismiss="modal" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

@endsection

BrainsterPreneurs/resources/views/layouts/navbar-pages.blade.php
@section('navbar-pages')
    <a href="{{route('my-projects.index')}}" class="nav-item nav-link text-dark font-weight-bold @if($page=='1') active @endif">My Projects</a>
    <a href="{{route('my-applications.index')}}" class="nav-item nav-link text-dark font-weight-bold @if($page=='2') active @endif">My Applications</a>
    <a href="{{route('my-profile.index')}}" class="nav-item nav-link text-dark font-weight-bold  @if($page=='3') active @endif">My Profile</a>
@endsection

BrainsterPreneurs/resources/views/layouts/registration.blade.php
@extends('layouts.app')
<main>
    <div class="container-fluid background-img-steps d-flex flex-column h-100">
        <div class="row h-100">
            <div class="col-12">
                <div class="row m-5 margin-left-steps">
                    <div class="col-4">
                        <h1 class="font-weight-bold">@yield('title')</h1>
                    </div>
                    <div class="col-8">
                        <hr style="border-top: 3px solid #dd7f1e; margin-top: 30px">
{{--                        <div style="border-width:2px; border-style:solid; border-color:black; margin-top: 30px"></div>--}}
                    </div>
                </div>

                @hasSection('sub-title')
                    <div class="row margin-left-steps">
                        <div class="col-12">
                            <h5 class="text-secondary mb-5">@yield('sub-title')</h5>
                        </div>
                    </div>
                @endif

            </div>

            <div class="col-12 h-100">
                @yield('form')
            </div>
        </div>
    </div>
</main>