BrainsterPreneurs/routes/web.php
<?php

use App\Http\Controllers\HomeController;
//use App\Http\Controllers\MyProjectsController;
//use App\Http\Controllers\StepOneController;
//use App\Http\Controllers\StepThreeController;
//use App\Http\Controllers\StepTwoController;
//use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::resource('/stepOne', StepOneController::class)->only(['index', 'store']);
Route::resource('/stepTwo', StepTwoController::class)->only(['index', 'store']);
Route::resource('/stepThree', StepThreeController::class)->only(['index', 'store']);
Route::post('/stepThree-media', StepThreeController::class . "@mediaStore")->name('stepThree-media.store');

Route::resource('/home/my-projects', MyProjectsController::class);

Route::get('/home/my-projects/profile/{user}/{project}', MyProjectsController::class . '@applicantProfile')->name('my-projects.profile');
Route::post('/home/acceptApplicant', MyProjectsController::class. '@applicantAccept');
Route::post('/home/my-projects/project', MyProjectsController::class. '@projectComplete');

Route::get('/user-avatar', UserController::class . '@getAvatar')->name('current-user-avatar.get');
Route::get('/user-avatar/{user}', UserController::class . '@getAvatarByUser')->name('user-avatar.get');

Route::resource('/home/my-applications', MyApplicationsController::class)->only(['index', 'destroy']);
Route::resource('/home/my-profile', MyProfileController::class);

Route::post('/home/applications', [HomeController::class, 'getApplications']);

BrainsterPreneurs/resources/views/_includes/home_cards.blade.php
<div class="cards">
    @foreach($projects as $project)
        <div style="margin: 0 100px 0 0; height: 210px;">
            @include('_includes.project-card', [
                        'project' => $project,
                        'showBadge' =>'0',
                        'first' => $loop->index == 0 ? 1 : 0,
                        'className' => '',
                        'isHome' => 1
                        ])
        </div>
    @endforeach
</div>
<nav aria-label="Page navigation example" style="margin-top: 8px; float: right">
    <ul class="pagination justify-content-center" id="application-paging">
        <li class="page-item @if($pageNumber==1) disabled @endif" data-pageNumber="-1">
            <a class="page-link" data-pageNumber="-1">Previous</a>
        </li>
        @for ($i = 1; $i <= $numberOfPages; $i++)
            <li class="page-item @if($pageNumber == $i) disabled @endif" data-pageNumber="{{ $i }}">
                <a class="page-link" data-pageNumber="{{ $i }}">{{ $i }}</a>
            </li>
        @endfor
        <li class="page-item @if($pageNumber==$numberOfPages) disabled @endif" data-pageNumber="-2">
            <a class="page-link" data-pageNumber="-2">Next</a>
        </li>
    </ul>
</nav>

BrainsterPreneurs/resources/views/_includes/project-applicants-card.blade.php
<div class="card text-center applicants-card ml-3 @if($projectMember->accepted == 1) accepted @endif">
    <div class="card-body">
        <form action="{{route('my-projects.profile', ['user'=> $projectMember->member->id, 'project' => $project])}}">
            <button type="submit">
                @if($projectMember->member->hasPhoto())
                    <img src="{{route('user-avatar.get', ['user' => $projectMember->member->id])}}" alt="" class="img-applicants" />
                @else
                    <img src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg" alt="" class="img-applicants" />
                @endif
            </button>
        </form>
        <h5 class="card-title">{{$projectMember->member->name}}</h5>
        <h6 class="card-subtitle mb-2 color-orange">profession: {{$projectMember->member->academy->name}}</h6>
        <div class="text-muted">{{$projectMember->member->email}}</div>
        <p class="card-text mt-3 mb-5 text-wrap">Message: {{$projectMember->message}}</p>
    </div>
    <div class="card-applicant-button position-absolute text-muted" data-projectid="{{$projectMember->project_id}}" data-userid="{{$projectMember->member->id}}">+</div>
</div>

BrainsterPreneurs/resources/views/_includes/project-card.blade.php
<div class="row cards-card @if(isset($first) && $first == '1') first @endif @if(isset($className)) {{$className}} @endif">
    <div class="col-12 mb-5">
        <div class="row m-0 cards-card--content">
            <div class="col-3 text-center">
                <div class="imgProjectCard-wrapper">
                    @if($project->owner->hasPhoto())
                        <img src="{{route('user-avatar.get', ['user' => $project->owner->id])}}"
                             alt=""/>
                    @else
                        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg"
                             alt=""/>
                    @endif
                    <div>
                        <h6>{{$project->owner->name}}</h6>
                    </div>
                    <div>
                        <div class="text-orange">I'm a {{$project->owner->academy->name}}</div>
                    </div>
                </div>

                <div>
                    <small class="font-xx-small font-weight-normal">I'm looking for</small>
                    <div class="row p-o m-0 justify-content-center mt-2">
                        @foreach($project->academies as $academy)
                            <div class="half-circle">
                                <div>
                                    <p class="pt-1 fontSize">{{$academy->name}}</p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="col-9">
                @if(request()->path() == "home/my-projects")
                    <form action="{{route('my-projects.show', ['my_project' => $project])}}" method="get">
                        <button type="submit" class="d-flex flex-column align-items-center text-light projectCard-applicant-circle">
                            <p class="mt-2 mb-0">{{$project->members->count()}}</p>
                            <div>Applicants</div>
                        </button>
                    </form>
                @else
                    <div class="d-flex flex-column align-items-center text-light projectCard-applicant-circle">
                        <p class="mt-2 mb-0">{{$project->members->count()}}</p>
                        <div>Applicants</div>
                    </div>
                @endif
                <div class="card-block mt-3 card-content-description">
                    <h6 class="card-title">{{$project->name}}</h6>
                    <p class="card-text pb-0 mb-0" id="text" style="font-size: smaller">
                        @if(strlen($project->description) > 150)
                            {{substr($project->description, 0, 150)}}
                        @else
                            {{$project->description}}
                        @endif
                    </p>
                    @if(strlen($project->description) > 150)
                        <span id="moreText" class="d-none">@if(strlen($project->description) > 150) {{substr($project->description, 150)}} @endif</span>
                    @endif

                    <div class="d-flex w-100 justify-content-end">
                        <button class="" id="textButton"><a href="#">Show More</a></button>
                    </div>
                </div>
                @if(isset($showBadge) && $showBadge == '1' && request()->path() == "home/my-projects")
                    @if($project->locked == 1)
                        <div class= "badge">
                            <img src="{{asset('/images/icons/badge.png')}}" alt="" >
                        </div>
                    @endif
                @endif
                @if(request()->path() == "home" || (isset($isHome) && $isHome == 1))
                    <button data-projectid="{{$project->id}}"
                            class="btn bg-secondary text-light text-center projectCard-btn float-right mt-5 @if($project->memberExists($user)) disabled @endif"
                            type="button">I'M IN</button>
                @endif

                @if(request()->path() == "home/my-applications")
                    <div class="application-respond">
                        <div class="d-flex">
                            @if(optional($project->projectMember->where('user_id', $user->id)->first())->accepted == 1)
                                    <span class="accepted text-muted">Application accepted</span>
                                    <img class="ml-2 w-5 h-5" src="{{asset('/images/icons/5.png')}}">
                            @else
                                <span class="denied text-danger">Application denied</span>
                                <img class="ml-2 w-5 h-5" src="{{asset('/images/icons/6.png')}}">
                            @endif
                        </div>
                    </div>
                @endif
            </div>
        </div>

        @if(isset($isEditable) && $isEditable == '1')
            <div class="controls">
                @if(request()->path() == "home/my-projects")
                    <img class="edit-delete-controls mb-3 delete-control" src="{{asset('/images/icons/7.png')}}" data-route="{{route('my-projects.destroy', ['my_project' => $project])}}" alt="">
                    <a href="{{route('my-projects.edit', ['my_project' => $project])}}"><img class="edit-delete-controls" src="{{asset('/images/icons/8.png')}}" alt=""></a>
                @endif
                @if(request()->path() == "home/my-applications"
                        && optional($project->projectMember->where('user_id', $user->id)->first())->accepted == 0)
                    <img class="edit-delete-controls remove-control" src="{{asset('/images/icons/2.png')}}" alt="" data-route="{{route('my-applications.destroy', ['my_application' => $project])}}">
                @endif

            </div>
        @endif
    </div>
</div>